### ISSUE TITLE
Error at Line 61: unknown instruction docker/amd64/dockerfile

### ISSUE THREAD

**Issue by jordanhandy** [davidjameshowell/bitwarden_rs_heroku#1]
Just came across this repo, and thought I'd give the steps a try for myself.
I've never used Docker before, in any major capacity, and have familiarity with Heroku, but not when it comes to pushing Docker images.

I tried running the shell script, and get an error at ln 61 (and subsequently ln 64).  The error is the subject of this error.  Seems like it can't parse the dockerfile from the bitwarden_rs dir?

Any steps on how to proceed here?
Thanks

**Comment by jordanhandy** [comment]
Resolved.  Was able to cp the Dockerfile located in the docker/amd64/dockerfile, and overwrite the Dockerfile in the base directory.  Build worked with this Dockerfile

**Comment by davidjameshowell** [comment]
So the upstream (bitwarden_rs) does a symlink for the Dockerfile in the root to `docker/amd64/Dockerfile`. It is possible if it is being built on a different machine type than some Unix (Ubuntu in my test case) it may fail on that. I'll look into just pointing directly at the amd64 file instead since that is what Heroku only will support.
`

**Comment by davidjameshowell** [comment]
I ended up incorporating your logic into it just to be safe and avoid symlinks. We're hacking the repo to bits anyways.
